name: gol_pouneh
description: Gol Pouneh Store.

publish_to: 'none'

version: 1.0.8+9

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  motion_toast:
    git: https://github.com/koukibadr/Motion-Toast.git
  antdesign_icons: ^0.0.3
  cached_network_image: ^3.2.2
  carousel_slider: ^4.1.1
  chewie: ^1.3.5
  cupertino_icons: ^1.0.5
  flutter_html: ^3.0.0-alpha.6
  flutter_phoenix: ^1.1.0
  flutter_slider_drawer: ^2.1.1
  google_nav_bar: ^5.0.6
  http: ^0.13.5
  badges: ^2.0.3
  infinite_scroll_pagination: ^3.2.0
#  motion_toast: ^2.2.3
  shamsi_date: ^1.0.1
  share_plus: ^6.2.0
  shared_preferences: ^2.0.15
#  sms_autofill: ^2.2.0
  url_launcher: ^6.1.6
  video_player: ^2.4.7
  webview_flutter: ^4.0.0
  location:
  image_picker: ^0.8.6
  dio: ^4.0.6
  flutter_map:
  image:
  latlong2:
  video_player_platform_interface:
  test_api:
  string_scanner:
  android_intent_plus:
  geolocator:
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  flutter_launcher_icons:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/launcher_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
  fonts:
    - family: IRANSans
      fonts:
        - asset: assets/fonts/IRANSansWeb(FaNum).ttf
